### ISSUE TITLE
Registering new SEA-12 planned Simulations

### ISSUE THREAD

**Issue by gredmond-mo** [WCRP-CORDEX/simulation-status#10]
Per https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/48#issuecomment-1898872524

Please could I register the following:

|domain | institute | contact | rcm_name | driving_model | ensemble | experiment | status | estimated_completion_date|
|SEA-12 | MOHC | G. Redmond | HadREM3-GA7-05 | ERA5 | | evaluation   | running | 2024-03 |
|SEA-12 | MOHC | G. Redmond | HadREM3-GA7-05 | EC-EARTH3-Veg | r1i1p1f1 | historical | running | 2024-04 |
|SEA-12 | MOHC | G. Redmond | HadREM3-GA7-05 | NorESM2-MM | r1i1p1f1 | historical | running | 2024-04 |
|SEA-12 | MOHC | G. Redmond | HadREM3-GA7-05 | UKESM1-0-LL | r1i1p1f2 | historical | running | 2024-04 |
|SEA-12 | MOHC | G. Redmond | HadREM3-GA7-05 | EC-EARTH3-Veg | r1i1p1f1 | ssp370 | planned | |
|SEA-12 | MOHC | G. Redmond | HadREM3-GA7-05 | NorESM2-MM | r1i1p1f1 | ssp370 | planned | |
|SEA-12 | MOHC | G. Redmond | HadREM3-GA7-05 | UKESM1-0-LL | r1i1p1f2 | ssp370 | planned | |

**Comment by jesusff** [comment]
Thank you! This is ready. Please, check that everything is OK here:
https://wcrp-cordex.github.io/simulation-status/CORDEX_CMIP6_status.html#SEA-12

To update your status/plans in the future, please just reopen this issue. I will close it now.
