### ISSUE TITLE
UDAG ICON-CLM simulations

### ISSUE THREAD

**Issue by jesusff** [WCRP-CORDEX/simulation-status#11]
Clarifications from C. Steger:
> In the CLM Community we have already decided that the UDAG runs will be ones that go intro the balanced matrix. The NUKLEUS runs do e.g. not have transient aerosol. The name of the configuration in the end will not be UDAG but something like C2IXXX. We have also not decided about the institution yet. Suggestions are CLMcom-UDAG, CLMcom-UDAG-DWD or KIT or BTU .. and CLMcom-DWD or KIT or BTU (as we had later in CMIP5). But what is certain, is that the UDAG runs plus the simulations with NorESM2-MM by Adam and with CMCC-CM2-SR5 by Heimo and CMCC colleagues will be ones for the balanced matrix.

**Comment by jesusff** [comment]
@csteger, is this run still planned (this is duplicated as DWD and UDAG)? Would it be with the NUKLEUS version?
https://github.com/WCRP-CORDEX/simulation-status/blob/3bbfa183f879546701a31b7a51fce319671e5a25/CMIP6_downscaling_plans.csv#L228
Or is it just a left over in the file (it also appears in the google doc)?

**Comment by csteger** [comment]
Yes this is a left over. This run will be done in UDAG. I have deleted it in the google doc.

**Comment by csteger** [comment]
Hi Chus, 

I saw yesterday, that the overview table is completely outdated regarding the CLMcom simulations. I will update it in the next days and also have a look at the other issues. 

Institution names should always be CLMcom-$INSTIUTION (e.g. CLMcom-KIT). 

@Hendrik: Is it okay if just transfer the information from our internal overview table to the official table? Or do you want to keep some of the NUKLEUS runs in?

Best wishes
Christian
