### ISSUE TITLE
Update status for BARPA-R1-NN

### ISSUE THREAD

**Issue by chunhsusu** [WCRP-CORDEX/simulation-status#19]
Please update  [simulation status table](https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html?search.search=barpa) as follows:
- Replace the contact person with my name (Chun-Hsu SU). Andrew (Dowdy) is not with the Bureau of Meteorology at this time. My contact email is chunhsu.su@bom.gov.au, if needed.
- Remove CNRM-ESM2-1 experiments for all scenarios. After testing, we have decided not to downscale CNRM.
- Update status for MPI-ESM1-2-HR/ssp126 to "completed"

**Comment by jesusff** [comment]
Thank you for the update, @chunhsusu. This is ready.

May I ask about CNRM-ESM2-1? Was it a problem particular to your simulations when nesting to this GCM? or you found problems with the GCM itself? This model is being used to drive simulations across many CORDEX domains.

**Comment by chunhsusu** [comment]
Hi @jesusff ,  

A CMIP6 model was only downscaled if BARPA-R preliminary runs produced a satisfactory scorecard. The scorecard assesses various aspects of model performance, such as the number of simulated east coast lows and tropical cyclones near Australia, temperature and precipitation biases, change signal differences between BARPA-R and global models for temperature and precipitation and temperature-precipitation correlation over Australia. Through this approach, CNRM-ESM2-1 was used due to e.g., pervasive cold biases in daily maximum temperature over Australia owing to upper-tropospheric temperature bias in the global model. 

Hope this helps. Sorry for not replying earlier, I didn't notice the assignment.

**Comment by jesusff** [comment]
No worries, I just assigned some people today to close some remaining open issues.

Thank you for your prompt reply. These details can be helpful for others. All clear with this explanation, so I close the issue now. Feel free to reopen if there are new updates.
