### ISSUE TITLE
ICTP update EURO-CORDEX status

### ISSUE THREAD

**Issue by graziano-giuliani** [WCRP-CORDEX/simulation-status#23]
Please update the CMIP6_downscaling_plans.csv:

https://github.com/WCRP-CORDEX/simulation-status/blob/0ecf4980c4fdba47fe8a4c797bad057db8a6839c/CMIP6_downscaling_plans.csv#L387  Status is now completed
https://github.com/WCRP-CORDEX/simulation-status/blob/0ecf4980c4fdba47fe8a4c797bad057db8a6839c/CMIP6_downscaling_plans.csv#L389 Status is now running
https://github.com/WCRP-CORDEX/simulation-status/blob/0ecf4980c4fdba47fe8a4c797bad057db8a6839c/CMIP6_downscaling_plans.csv#L390 Status is now completed
https://github.com/WCRP-CORDEX/simulation-status/blob/0ecf4980c4fdba47fe8a4c797bad057db8a6839c/CMIP6_downscaling_plans.csv#L392 Status is now running
https://github.com/WCRP-CORDEX/simulation-status/blob/0ecf4980c4fdba47fe8a4c797bad057db8a6839c/CMIP6_downscaling_plans.csv#L393 status is now running

**Comment by jesusff** [comment]
Thank you! this is updated now
