### ISSUE TITLE
Clarify NUKLEUS and CORDEX-CMIP6 simulations

### ISSUE THREAD

**Issue by jesusff** [WCRP-CORDEX/simulation-status#26]
Dear @HendrikFeldmannKIT @csteger

We had pending the disentangling of some CLMcom simulations which contributed to the NUKLEUS project. For ICON (#11) we added a name ICON-CLM-NUKLEUS in order to distinguish those runs from the newer ones. I'm not sure if the same applies to COSMO-CLM (that the version used in NUKLEUS is different to that to be used in UDAG). I wanted to confirm that you wanted to keep the NUKLEUS runs in the CORDEX-CMIP6 list (i.e. they will be published to ESGF at some point).

Related to this, there was some small issue to be clarified with the institutions (CLMcom-KIT, CLMcom-Hereon-KIT) and the runs they produced (https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/158).

The only point is to try to clarify how would you like to show up in tables such as:
https://wcrp-cordex.github.io/simulation-status/CORDEX_CMIP6_status_by_experiment.html#EUR-12-CCLMcom
https://wcrp-cordex.github.io/simulation-status/CORDEX_CMIP6_status_by_experiment.html#EUR-12-ICLMcom
https://wcrp-cordex.github.io/simulation-status/CORDEX_CMIP6_status_by_experiment.html#EUR-12-NUKLEUS

Do they look fine to you? Would you like to define a similar one for UDAG? Should we drop some simulations?

There is no rush. This issue can remain open for a while until you have some final names (source_ids) for the different model versions. Or we can use some interim solution to clarify a bit the tables. For example, would a COSMO-CLM-NUKLEUS name help to distinguish older model versions from the new runs? We are also discussing some variants with a different urban representation (#25).

**Comment by csteger** [comment]
Hi Chus,

I saw yesterday, that the overview table is completely outdated regarding the CLMcom simulations. I will update it in the next days and also have a look at the other issues.

Institution names should always be CLMcom-$INSTIUTION (e.g. CLMcom-KIT).

@Hendrik: Is it okay if just transfer the information from our internal overview table to the official table? Or do you want to keep some of the NUKLEUS runs in?

Best wishes
Christian

**Comment by HendrikFeldmannKIT** [comment]
Hi Christian,

it's OK to transfer the table. Some simulations done by NUKLEUS are included in the CLMcom table already (the CCLM6 ERA5 simulation for instance)

Cheers

Hendrik

**Comment by HendrikFeldmannKIT** [comment]
Hi Chus,
we won't use the existing NUKLEUS simulations. However, as a contribution to the CORDEX CMIP6 efforts, NUKLEUS will perform some simulations (with CCLM), which are in line with the CORDEX CMIP6 protocol and the other CLMcom contributions. There is no need to account for them separetely. Sorry for the confusion. These simulations are planned (and not finished like the old ones), but hopefully are started very soon.

Cheers

Hendrik

**Comment by jesusff** [comment]
Thank you, @csteger for updating the CSV file. I just had to make very small fixes (06c1fbd). I noticed, though that the balanced matrix is not balanced any more, as two ICON simulations dropped (this is the [old table](https://html-preview.github.io/?url=https://github.com/WCRP-CORDEX/simulation-status/blob/cd47b4b938525eb7580e214fbdc74bde8ca9f367/docs/CORDEX_CMIP6_status_by_experiment.html#EUR-12) and the [new one](https://html-preview.github.io/?url=https://github.com/WCRP-CORDEX/simulation-status/blob/caf3467d5ddc52e635d9e3d09f9fe695993c6a63/docs/CORDEX_CMIP6_status_by_experiment.html#EUR-12)). Not sure if this was intended (missing #EURbalanced label) or shall I bring them back? (the simulations exist, as performed by BTU and Hereon)

Also, COSMO-CLM dropped entirely from the balanced matrix?

**Comment by csteger** [comment]
Hi Chus. 
I will check the simulations for the balanced matrix. Maybe I made a mistake. This should not change compared to the initial plan. For COSMO-CLM it is a bit difficult. I think we said in one meeting, that we will use ICON for the balanced matrix, because both ICON and COSMO would do the same runs. But this has changed in the meantime. At least for ICON we will fill up the whole matrix and would be flexible with the runs that we contribute to the balanced matrix. In my opinion it would be ideal if we could extend the balanced matrix in a way that simulations of both models can be included.

**Comment by jesusff** [comment]
Yes, there are currently also 5 GCMs planned to be downscaled with COSMO. There should be a way to extend the matrix to fit it.

Your PR #30 fixed the ICON runs for the balanced matrix, so I think we can close this issue.

You finally didn't add #UDAG tags to the corresponding simulations. If you like, we can create an entry in the experiment list to show the UDAG simulations.

**Comment by csteger** [comment]
Sorry, I forgot to add the UDAG tag. I will do it and create a new merge request.

**Comment by csteger** [comment]
I have added #UDAG and created a merge request.

**Comment by jesusff** [comment]
Great. Thank you.

This is how it looks: https://wcrp-cordex.github.io/simulation-status/CORDEX_CMIP6_status_by_experiment.html#EUR-12-UDAG

Let me know if you prefer to show it in some other way (the contents are managed in [this file](https://github.com/WCRP-CORDEX/simulation-status/blob/main/CORDEX_CMIP6_experiments.yaml#L75-L80)). Otherwise, we can close this issue.

**Comment by csteger** [comment]
Looks good. The historcial simulations have been started last week. I changed the status to "running" and created another merge requst.

**Comment by jesusff** [comment]
Perfect, thank you. It is merged now. I close here, then.
