### ISSUE TITLE
Nam-12 simulations updates from Ouranos

### ISSUE THREAD

**Issue by dompaq** [WCRP-CORDEX/simulation-status#28]
updates for Ouranos in file CMIP6_downscaling_plans.csv
lines 496 and ss

- [x] 496 NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,CanESM5,r1i1p2f1,ssp585,completed,2024-12

- [x] 510 NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,NorESM2-MM,r1i1p1f2,historical,completed,2024-12
- [ ] 511 NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,NorESM2-MM,r1i1p1f2,ssp126,planned,2024-12
- [x] new line NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,NorESM2-MM,r1i1p1f2,ssp245,running,2024-12
- [x] 512 NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,NorESM2-MM,r1i1p1f2,ssp370,running,2024-12

- [x] 504 NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,MPI-ESM1-2-LR,r1i1p1f1,ssp245,completed,2024-12,
- [x] new line NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,MPI-ESM1-2-LR,r2i1p1f1,historical,completed
- [x] new line NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,MPI-ESM1-2-LR,r2i1p1f1,ssp370, running
- [x] new line NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,MPI-ESM1-2-LR,r3i1p1f1,historical,completed
- [x] new line NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,MPI-ESM1-2-LR,r3i1p1f1,ssp370, running
- [x] new line NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,MPI-ESM1-2-LR,r4i1p1f1,historical,planned
- [x] new line NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,MPI-ESM1-2-LR,r4i1p1f1,ssp370, planned
- [x] new line NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,MPI-ESM1-2-LR,r5i1p1f1,historical,planned
- [x] new line NAM-12,Ouranos,D. Paquin / C. McCray,CRCM5-SN,MPI-ESM1-2-LR,r5i1p1f1,ssp370, planned

**Comment by jesusff** [comment]
Thank you, Dominique. This is updated (please, check) except for the unchecked simulation above which seems unchanged from the existing status. Is it maybe running or completed, instead of planned?

**Comment by dompaq** [comment]
Thanks for the quick update! The difference in the line 511 is the model. There is a mistake in the name of the model (we are using NorESM2-MM and not LM).

**Comment by dompaq** [comment]
It's also need to be corrected for the other NorESM simulations

**Comment by jesusff** [comment]
Ups, sorry, I see. This is fixed in the next commit.

Thanks for the update!
