### ISSUE TITLE
Dynamical Downscaling CMIP6 over Southeast Asia

### ISSUE THREAD

**Issue by ploan** [WCRP-CORDEX/simulation-status#4]
Dear WCRP-CORDEX Progamme, 

My name is Phuong Loan Nguyen, a Research Associate from the Climate Change Research Centre (CCRC), UNSW Sydney. 
Our research group would like to update our contribution (Dynamical downscaling CMIP6 over Southeast Asia - SEA-22) to the CORDEX community. I already added the detailed information on Google document at https://docs.google.com/document/d/1Jy53yvB9SDOiWcwKRJc_HpWVgmjxZhy-qVviHl6ymDM/edit. 

I wonder whether I should update it anywhere else. 

Thank you in advance and I am looking forward to hearing from you. 

Cheers, 
Phuong Loan

**Comment by jesusff** [comment]
Dear @ploan , thanks for the update. It is now in place. Please, check if it looks OK
https://wcrp-cordex.github.io/simulation-status/CORDEX_CMIP6_status.html#SEA-22

**Comment by ploan** [comment]
> Dear @ploan , thanks for the update. It is now in place. Please, check if it looks OK https://wcrp-cordex.github.io/simulation-status/CORDEX_CMIP6_status.html#SEA-22

Hi Jesus, 
That's perfect. Thank you so much for your confirmation 
Cheers, 
Phuong Loan

**Comment by jesusff** [comment]
Yes, sorry. I should have noticed it. I fix it now and close the issue.
