### ISSUE TITLE
Evaluation run COSMO-CLM_URB by CLMcom-CMCC

### ISSUE THREAD

**Issue by marioRaffa** [WCRP-CORDEX/simulation-status#41]
**Evaluation run**
domain: EUR-12 
experiment: evaluation (ERA5-driven)
period: (spinup1979) 1980 - 2021
source_id: COSMO-CLM_URB ( pending issue https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/216 )
institution_id: CLMcom-CMCC
status: completed

**Comment by jesusff** [comment]
Thank you, Mario. This is also related to #25, right? There were some open questions there, that we should try to clear up and merge that PR before this update.

**Comment by jesusff** [comment]
I think this is ready. Please, search for your name in https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html and reopen the issue if necessary
