### ISSUE TITLE
CNRM-ALADIN64P1 Simulations

### ISSUE THREAD

**Issue by Hanhle-CLIPSSA** [WCRP-CORDEX/simulation-status#42]
domain,institute,contact,rcm_name,driving_model,ensemble,experiment,status,estimated_completion_date,comments
AUS-20i,IRD-MF,H.H. Le / M. Gévaudan,CNRM-ALADIN64P1,ERA5,,evaluation,completed,2024-09,
AUS-20i,IRD-MF,H.H. Le / M. Gévaudan,CNRM-ALADIN64P1,CNRM-ESM2-1,r1i1p1f2,historical,completed,2024-09,
AUS-20i,IRD-MF,H.H. Le / M. Gévaudan,CNRM-ALADIN64P1,CNRM-ESM2-1,r1i1p1f2,ssp370,running,2025-01,

**Comment by jesusff** [comment]
Thank you. Added

**Comment by Hanhle-CLIPSSA** [comment]
Thank you so much!
