### ISSUE TITLE
Comparison of precipitation data in different models

### ISSUE THREAD

**Issue by Maryam71276** [WCRP-CORDEX/simulation-status#43]
Precipitation data in each scenario and in climate change models are different from each other. We show it based on validation.

**Comment by Maryam71276** [comment]
provide CORDEX-CMIP6 data

**Comment by gnikulin** [comment]
@Maryam71276 , it's not clear what kind of issue you have. Here, the CORDEX modelling groups only provide information about status of their CORDEX-CMIP6 simulations. The CORDEX-CMIP6 simulations are not publicly available yet and will be provided through the Earth System Grid Federation (ESGF). There will be an announcement when the first CORDEX-CMIP6 simulations are available. You can subscribe for CORDEX news here https://cordex.org/about/3591-2/
