### ISSUE TITLE
Evaluation run COSMO-CLM_URB-ESG by CLMcom-KUL

### ISSUE THREAD

**Issue by Ivanderkelen** [WCRP-CORDEX/simulation-status#45]
Evaluation run
domain: EUR-12
experiment: evaluation (ERA5-driven)
period: (spinup1979) 1980 - 2023
source_id: CCLM6-0-1-URB-ESG ( pending issue https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/239)
institution_id: CLMcom-KUL (pending issue https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/238)
status: completed

**Comment by jesusff** [comment]
Thanks! Please, search for your name in https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html and reopen the issue if necessary
